apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nestjs-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nestjs
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default